name: Cloudflare
on: 
  workflow_dispatch:
    inputs:
        tags:
          description: 'Quack!'


jobs:
  build:
    runs-on: ubuntu-latest
    name: Quack
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - name: pwd
        run: 'pwd'
      - name: install
        run: 'npm install'
      - name: wrangle
        run: 'npx wrangler --help'
      - name: Quack
        run: "echo bop bop"
        