name: Cloudflare
on: 
  workflow_dispatch:
    inputs:
        tags:
          description: 'Quack!'


jobs:
  build:
    runs-on: ubuntu-latest
    name: Quack
    env:
      working-directory: ./api
    steps:
      - name: install
        run: 'npm install'
      - name: wrangle
        run: 'npx wrangler --help'
      - name: Quack
        run: "echo bop bop"
        